name = "Generic Dinner"
category = "Main"

ingredients = [
  "Ingredients can be input here",
  "as an array.",
]

steps = [
  "Steps can be input here",
  "as an array.",
]

[groups.sauce]
name = "Sauce"

ingredients = [
  "For recipes that break steps apart",
  "special ingredients can be input here",
  "as an array.",
]

steps = [
  "For recipes that break steps apart",
  "special steps can be input here",
  "as an array.",
]

[groups.bread]
name = "Bread"

ingredients = [
  "For recipes that break steps apart",
  "special ingredients can be input here",
  "as an array.",
]

steps = [
  "For recipes that break steps apart",
  "special steps can be input here",
  "as an array.",
]
