name = "Generic Dinner"
category = "Main"
include_in_cookbook = true
source = "My Great Cookbook p.12"
# default text size is 12, but can be set like so:
# text_size = 10

ingredients = [
  "Ingredients can be input here",
  "as an array.",
  "Use the following format",
  "14 oz can; Diced Tomatoes (do not drain)",
  "quantity; name (optional notes)",
  "quantity; name",
]

steps = [
  "Steps can be input here",
  "as an array.",
]

[groups.sauce]
name = "Sauce"

ingredients = [
  "For recipes that break steps apart",
  "special ingredients can be input here",
  "as an array.",
]

steps = [
  "For recipes that break steps apart",
  "special steps can be input here",
  "as an array.",
]

[groups.bread]
name = "Bread"

ingredients = [
  "For recipes that break steps apart",
  "special ingredients can be input here",
  "as an array.",
]

steps = [
  "For recipes that break steps apart",
  "special steps can be input here",
  "as an array.",
]
